---
apiVersion: v1
kind: Service
metadata:
  name: cicd-jenkins-svc
  namespace: devops-tools
spec:
  selector:
    app: cicd-jenkins
  type: LoadBalancer
  ports:
  - name: cicd-jenkins
    protocol: TCP
    port: 8000
    targetPort: 8000